# Generated by Django 3.2.5 on 2021-07-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedroom_amount', models.IntegerField()),
                ('bathroom_amount', models.IntegerField()),
                ('house_floor', models.IntegerField()),
                ('garage_amount', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('house_image', models.ImageField(upload_to='main_images')),
                ('secondary_image', models.ImageField(upload_to='secondary_images')),
            ],
        ),
    ]
